name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhemApproved:
    runs-on: ubuntu-latest
    steps:
    - name: Labelwhenapproved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
        REMOVE_LABEL: "awaiting%20review"
